### PR TITLE
added clip to read_sysex

### PR DESCRIPTION
**Pull request by omit66**
This fixes the following error for me: 

```
Traceback (most recent call last):
...
    self.mid = MidiFile(filename)
  File ".../site-packages/mido/midifiles/midifiles.py", line 316, in __init__
    self._load(file)
  File ".../site-packages/mido/midifiles/midifiles.py", line 353, in _load
    clip=self.clip))
  File ".../site-packages/mido/midifiles/midifiles.py", line 218, in read_track
    msg = read_sysex(infile, delta)
  File ".../site-packages/mido/midifiles/midifiles.py", line 152, in read_sysex
    return Message('sysex', data=data, time=delta)
  File ".../site-packages/mido/messages/messages.py", line 88, in __init__
    check_msgdict(msgdict)
  File ".../site-packages/mido/messages/checks.py", line 99, in check_msgdict
    check_value(name, value)
  File ".../site-packages/mido/messages/checks.py", line 86, in check_value
    _CHECKS[name](value)
  File ".../site-packages/mido/messages/checks.py", line 37, in check_data
    check_data_byte(byte)
  File ".../site-packages/mido/messages/checks.py", line 58, in check_data_byte
    raise ValueError('data byte must be in range 0..127')
ValueError: data byte must be in range 0..127
```

I found the similar [issue 63](https://github.com/mido/mido/issues/63).

I think cliping should be done before creating the Message.

### CODE REVIEW

**Comment by cameronmantell** [comment]
Hi there, 
Would this fix my issue (#230 ) ?
Thanks

**Comment by omit66** [comment]
@cameronmantell As far as I can see, you are calling read_sysex as well. 
Then this should fix your issue too!

**Comment by cameronmantell** [comment]
@omit66 I can confirm that your code worked! 
I replaced the original mido library with your repo using the command below:
`pip install --upgrade https://github.com/omit66/mido/tarball/master`
I can now read the midi file that was giving me issues before by using the clip functionality.
Thank you!

**Comment by duhaime** [comment]
@olemb if you could take a look at this PR as well, it'd be great! I've hit this same error, and it'd be great to have a fix!

**Comment by olemb** [comment]
We somehow overlooked this when adding the `clip` option. Thanks for the fix!

**Review by olemb — APPROVED** [review]
Looks good.

**Pull request merged**
