### PR TITLE
Fix PortServer disconnect crash in Python 3

### LINKED ISSUE #290: PortServer crashes on client disconnect in Python 3
In Python 3, `PortServer` crashes with the following exception when a socket client (``mido.sockets.connect``) disconnects.
```
Traceback (most recent call last):
  File "m_server.py", line 21, in <module>
    for message in client.iter_pending():
  File "/usr/lib/python3/dist-packages/mido/ports.py", line 175, in iter_pending
    msg = self.poll()
  File "/usr/lib/python3/dist-packages/mido/ports.py", line 229, in poll
    return self.receive(block=False)
  File "/usr/lib/python3/dist-packages/mido/ports.py", line 212, in receive
    msg = self._receive(block=block)
  File "/usr/lib/python3/dist-packages/mido/sockets.py", line 112, in _receive
    self._parser.feed_byte(ord(byte))
TypeError: ord() expected a character, but string of length 0 found
```
Tested in mido 1.2.9, 2f53ba0bfa4c0fc5949bd5802d9cb03366e34317.

----------------

Test server code:
```python
#Taken directly from https://mido.readthedocs.io/en/latest/socket_ports.html

from mido.sockets import PortServer

with PortServer('localhost', 8080) as server:
    clients = []
    while True:
        # Handle connections.
        client = server.accept(block=False)
        if client:
            print('Connection from {}'.format(client.name))
            clients.append(client)

        for i, client in reversed(list(enumerate(clients))):
            if client.closed:
                print('{} disconnected'.format(client.name))
                del clients[i]

        # Receive messages.
        for client in clients:
            for message in client.iter_pending():
                print('Received {} from {}'.format(message, client))
```
Test client code:
```python
import mido
import mido.sockets
import time

with mido.sockets.connect('localhost', 8080) as c:
    for _ in range(5):
        c.send(mido.Message('note_on'))
        time.sleep(0.25)
```

Server output when run with Python 2.7.18:
```
Connection from 127.0.0.158706
Received note_on channel=0 note=0 velocity=64 time=0 from <open I/O port '127.0.0.158706' (SocketPort)>
Received note_on channel=0 note=0 velocity=64 time=0 from <open I/O port '127.0.0.158706' (SocketPort)>
Received note_on channel=0 note=0 velocity=64 time=0 from <open I/O port '127.0.0.158706' (SocketPort)>
Received note_on channel=0 note=0 velocity=64 time=0 from <open I/O port '127.0.0.158706' (SocketPort)>
Received note_on channel=0 note=0 velocity=64 time=0 from <open I/O port '127.0.0.158706' (SocketPort)>
127.0.0.158706 disconnected
```

Server output when run with Python 3.8.5:
```
Connection from 127.0.0.158740
Received note_on channel=0 note=0 velocity=64 time=0 from <open I/O port '127.0.0.158740' (SocketPort)>
Received note_on channel=0 note=0 velocity=64 time=0 from <open I/O port '127.0.0.158740' (SocketPort)>
Received note_on channel=0 note=0 velocity=64 time=0 from <open I/O port '127.0.0.158740' (SocketPort)>
Received note_on channel=0 note=0 velocity=64 time=0 from <open I/O port '127.0.0.158740' (SocketPort)>
Traceback (most recent call last):
  File "m_server.py", line 21, in <module>
    for message in client.iter_pending():
  File "/usr/lib/python3/dist-packages/mido/ports.py", line 175, in iter_pending
    msg = self.poll()
  File "/usr/lib/python3/dist-packages/mido/ports.py", line 229, in poll
    return self.receive(block=False)
  File "/usr/lib/python3/dist-packages/mido/ports.py", line 212, in receive
    msg = self._receive(block=block)
  File "/usr/lib/python3/dist-packages/mido/sockets.py", line 112, in _receive
    self._parser.feed_byte(ord(byte))
TypeError: ord() expected a character, but string of length 0 found
```

### PR DESCRIPTION
**Pull request by kyleclaassen**
Fixes #290.  More info is available [here](https://github.com/kyleclaassen/mido/commit/f38bbd703b4114c2bd70ac7e4cad2d58d01c44e7#commitcomment-47639569).

### CODE REVIEW

**Comment by phyordia** [comment]
+1 for this fix. Thank you @kyleclaassen. This also fixes other subsequent issues, such the first message received on the server being dropped (in your example, only 4 messages are received by the server), as well has note_on being sent and note_off being received (not shown in your example, but I experience it).

Why almost year later this isn't merged?

**Comment by rdoursenaud** [comment]
Thanks @phyordia for confirming the fix is effective.
To answer why it hasn't been merged: unfortunately mido's maintainer (@olemb) has been MIA since mid 2021 for personal reasons and afaik is the only one to have the permissions.
We may need to fork the project at some point to ensure its future.

**Comment by phyordia** [comment]
Gotcha! Hope everything is ok with him. I made a fork and implemented your fix plus another one(s)... definitely users should converge on an official active fork that everyone contributes to... anyway, thanks again for this

**Review by olemb — COMMENTED** [review]
Ah, I see what I did wrong. It was supposed to say

    if byte == b'':

Your code shows the intent more clearly though so it's better than mine.

**Review by olemb — APPROVED** [review]

**Comment by olemb** [comment]
Thank you for the fix!

**Pull request merged**
