### PR TITLE
Added original logo SVG file and PNG render.

### PR DESCRIPTION
**Pull request by olemb**
(Needs some cleanup, as described in issue #277.)

### CODE REVIEW

**Comment by olemb** [comment]
Tests failed:

```
missing from sdist:
  logo
  logo/README.md
  logo/mido.png
  logo/mido.svg
suggested MANIFEST.in rules:
  recursive-include logo *.md
  recursive-include logo *.png
  recursive-include logo *.svg
ERROR: InvocationError for command /home/travis/build/mido/mido/.tox/py27/bin/check-manifest -v (exited with code 1)
```

I don't think the logo should be included in the package.

**Comment by olemb** [comment]
Added a `prune` line for it.

**Comment by olemb** [comment]
Nice, I actually got an email when the tests failed.

**Review by bast — APPROVED** [review]
Just want to mention an alternative: what some projects do is to create a separate repository for artwork.

**Comment by olemb** [comment]
Thanks!

**Pull request merged**
