### PR TITLE
Remove remnants of Python 2 support

### PR DESCRIPTION
**Pull request by rdoursenaud**
- Removed a no longer required statement
- Removed __future__ imports
- Updated shebangs to explicitly require python3
- Updated documentation samples to explicitly call python3
- Used standard syntax for @classmethod parameter
- Removed useless test in Python 3

### CODE REVIEW

**Comment by rdoursenaud** [comment]
This improves on the work of #408.

**Review by olemb — APPROVED** [review]

**Comment by olemb** [comment]
A, nice! I didn't even consider these.

**Comment by rdoursenaud** [comment]
I don't think you meant closing the PR but rather merge it.

**Comment by olemb** [comment]
I'm sure I merged it but apparently not. Good that you caught it.

**Comment by rdoursenaud** [comment]
No problem :)

**Pull request merged**
